version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: my-jenkins-3
    volumes:
      - C:\Users\hp.1\Desktop\DevOps\Class2\Docker_Setup\jenkin_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

